name: "generate-docs"
on:
  workflow_dispatch:
  push:
    branches:
      - master
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.20.3'
permissions:
  contents: read

jobs:
  generate-docs:
    if: github.repository == 'kubernetes/minikube'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753
        with:
          go-version: ${{env.GO_VERSION}}
          cache-dependency-path: ./go.sum
      - name: Generate Docs
        id: gendocs
        run: |
          make generate-docs
          c=$(git status --porcelain)
          c="${c//$'\n'/'%0A'}"
          c="${c//$'\r'/'%0D'}"
          # The following is to support multiline with GITHUB_OUTPUT, see https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
          echo "changes<<EOF" >> $GITHUB_OUTPUT
          echo "$c" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Create PR
        if: ${{ steps.gendocs.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@5b4a9f6a9e2af26e5f02351490b90d01eb8ec1e5
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: Update auto-generated docs and translations
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: gendocs
          push-to-fork: minikube-bot/minikube
          base: master
          delete-branch: true
          title: 'Update auto-generated docs and translations'
          body: |
            Committing changes resulting from `make generate-docs`.
            This PR is auto-generated by the [gendocs](https://github.com/kubernetes/minikube/blob/master/.github/workflows/docs.yml) CI workflow.

            ```
            ${{ steps.gendocs.outputs.changes }}
            ```
